FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --loglevel verbose
RUN npm install -g @adonisjs/cli --loglevel verbose
RUN npm install @adonisjs/mail --loglevel verbose
