INSERT INTO planosaude (nome) VALUES ('Amil');
INSERT INTO planosaude (nome) VALUES ('Bradesco Saúde');
INSERT INTO planosaude (nome) VALUES ('Unimed');
INSERT INTO planosaude (nome) VALUES ('SulAmérica Saúde');
INSERT INTO planosaude (nome) VALUES ('Hapvida');
INSERT INTO planosaude (nome) VALUES ('NotreDame Intermédica');
INSERT INTO planosaude (nome) VALUES ('Prevent Senior');
INSERT INTO planosaude (nome) VALUES ('Porto Seguro Saúde');
INSERT INTO planosaude (nome) VALUES ('GreenLine Sistema de Saúde');
INSERT INTO planosaude (nome) VALUES ('Grupo São Francisco');
INSERT INTO planosaude (nome) VALUES ('Mediservice');
INSERT INTO planosaude (nome) VALUES ('Santa Helena Saúde');
INSERT INTO planosaude (nome) VALUES ('Caixa Seguradora Saúde');
INSERT INTO planosaude (nome) VALUES ('Golden Cross');
INSERT INTO planosaude (nome) VALUES ('Seguros Unimed');
INSERT INTO planosaude (nome) VALUES ('One Health');
INSERT INTO planosaude (nome) VALUES ('Grupo Allianz');
INSERT INTO planosaude (nome) VALUES ('Sompo Saúde');
INSERT INTO planosaude (nome) VALUES ('Trasmontano Saúde');
INSERT INTO planosaude (nome) VALUES ('Liberty Seguros');
INSERT INTO planosaude (nome) VALUES ('Mapfre Saúde');
INSERT INTO planosaude (nome) VALUES ('Biovida Saúde');
INSERT INTO planosaude (nome) VALUES ('Sami Saúde');
INSERT INTO planosaude (nome) VALUES ('São Cristóvão Saúde');
INSERT INTO planosaude (nome) VALUES ('Santa Tereza Saúde');
INSERT INTO planosaude (nome) VALUES ('Paraná Clínicas');
INSERT INTO planosaude (nome) VALUES ('Saúde Sim');
INSERT INTO planosaude (nome) VALUES ('Affix Saúde');
INSERT INTO planosaude (nome) VALUES ('Agemed Saúde');
INSERT INTO planosaude (nome) VALUES ('Ameplan Saúde');
INSERT INTO planosaude (nome) VALUES ('Benevix');
INSERT INTO planosaude (nome) VALUES ('Care Plus');
INSERT INTO planosaude (nome) VALUES ('Clinipam');
INSERT INTO planosaude (nome) VALUES ('Conmed Saúde');
INSERT INTO planosaude (nome) VALUES ('Doctor Clin');
INSERT INTO planosaude (nome) VALUES ('GNDI (Grupo NotreDame Intermédica)');
INSERT INTO planosaude (nome) VALUES ('Life Day Saúde');
INSERT INTO planosaude (nome) VALUES ('Plano São Lucas Saúde');
INSERT INTO planosaude (nome) VALUES ('Serpram');
INSERT INTO planosaude (nome) VALUES ('Total MedCare');
INSERT INTO planosaude (nome) VALUES ('Plamed Saúde');
INSERT INTO planosaude (nome) VALUES ('Plan Assiste');
INSERT INTO planosaude (nome) VALUES ('Promed Assistência Médica');
INSERT INTO planosaude (nome) VALUES ('Saúde Beneficência Portuguesa');
INSERT INTO planosaude (nome) VALUES ('Saúde Bradesco');
INSERT INTO planosaude (nome) VALUES ('São Bernardo Saúde');
INSERT INTO planosaude (nome) VALUES ('Saúde Caixa');
INSERT INTO planosaude (nome) VALUES ('São Francisco Saúde');
INSERT INTO planosaude (nome) VALUES ('Saúde Itaú');
INSERT INTO planosaude (nome) VALUES ('São Miguel Saúde');
INSERT INTO planosaude (nome) VALUES ('Seisa Saúde');
INSERT INTO planosaude (nome) VALUES ('Serra Saúde');
INSERT INTO planosaude (nome) VALUES ('Sinam');
INSERT INTO planosaude (nome) VALUES ('Smile Saúde');
INSERT INTO planosaude (nome) VALUES ('SPTrans');
INSERT INTO planosaude (nome) VALUES ('SulAmérica Saúde');
INSERT INTO planosaude (nome) VALUES ('Transmontano Saúde');
INSERT INTO planosaude (nome) VALUES ('Unafisco Saúde');
INSERT INTO planosaude (nome) VALUES ('Unihosp Saúde');
INSERT INTO planosaude (nome) VALUES ('Universal Saúde');
INSERT INTO planosaude (nome) VALUES ('Vale Saúde');
INSERT INTO planosaude (nome) VALUES ('Vitallis Saúde');
INSERT INTO planosaude (nome) VALUES ('Amil Dental');
INSERT INTO planosaude (nome) VALUES ('Bradesco Dental');
INSERT INTO planosaude (nome) VALUES ('OdontoPrev');
INSERT INTO planosaude (nome) VALUES ('SulAmérica Odonto');
INSERT INTO planosaude (nome) VALUES ('Unimed Odonto');
INSERT INTO planosaude (nome) VALUES ('MetLife Dental');
INSERT INTO planosaude (nome) VALUES ('Interodonto');
INSERT INTO planosaude (nome) VALUES ('Porto Seguro Odontológico');
INSERT INTO planosaude (nome) VALUES ('NotreDame Odontológica');
INSERT INTO planosaude (nome) VALUES ('DentalCorp');
INSERT INTO planosaude (nome) VALUES ('Prodent');
INSERT INTO planosaude (nome) VALUES ('Docctor Med Odonto');
INSERT INTO planosaude (nome) VALUES ('Inpao Dental');
INSERT INTO planosaude (nome) VALUES ('Odontosystem');
INSERT INTO planosaude (nome) VALUES ('Uniodonto');
INSERT INTO planosaude (nome) VALUES ('OdontoCompany');
INSERT INTO planosaude (nome) VALUES ('Dental Uni');
INSERT INTO planosaude (nome) VALUES ('Dentistas Associados');
INSERT INTO planosaude (nome) VALUES ('Odonto Serv');
INSERT INTO planosaude (nome) VALUES ('Odonto Empresas');
INSERT INTO planosaude (nome) VALUES ('Dental Par');
INSERT INTO planosaude (nome) VALUES ('GreenLine Odontológico');
INSERT INTO planosaude (nome) VALUES ('Ideal Odonto');
INSERT INTO planosaude (nome) VALUES ('Liberty Dental');
INSERT INTO planosaude (nome) VALUES ('Odonto Santander');
INSERT INTO planosaude (nome) VALUES ('Sorriso Assistência Odontológica');
INSERT INTO planosaude (nome) VALUES ('Saúde Caixa Odonto');
INSERT INTO planosaude (nome) VALUES ('SulAmérica Odonto PME');
INSERT INTO planosaude (nome) VALUES ('Uniodonto Paulista');
INSERT INTO planosaude (nome) VALUES ('Vale Dental');
INSERT INTO planosaude (nome) VALUES ('Particular');